//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tynamix.ObjectFiller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tynamix.ObjectFiller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron;Abbey;Abbie;Abby;Abdul;Abe;Abel;Abigail;Abraham;Abram;Ada;Adah;Adalberto;Adaline;Adam;Adam;Adan;Addie;Adela;Adelaida;Adelaide;Adele;Adelia;Adelina;Adeline;Adell;Adella;Adelle;Adena;Adina;Adolfo;Adolph;Adria;Adrian;Adrian;Adriana;Adriane;Adrianna;Adrianne;Adrien;Adriene;Adrienne;Afton;Agatha;Agnes;Agnus;Agripina;Agueda;Agustin;Agustina;Ahmad;Ahmed;Ai;Aida;Aide;Aiko;Aileen;Ailene;Aimee;Aisha;Aja;Akiko;Akilah;Al;Alaina;Alaine;Alan;Alana;Alane;Alanna;Alayna;Alba;Albert;Albert;Alberta;Albertha;Albertina;Al [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string firstNames {
            get {
                return ResourceManager.GetString("firstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-Weg;Aachener Str.;Abbestr.;Achtbeeteweg;Ackermannstr.;Adalbert-Stifter-Weg;Adlergasse;Adolfstr.;Agnes-Smedley-Str.;Ahlbecker Str.;Ahornstr.;Ahornweg;Akazienweg;Alaunplatz;Alaunstr.;Albert-Hensel-Str.;Albert-Richter-Str.;Albert-Schweitzer-Str.;Albert-Wolf-Platz;Albertplatz;Albertstr.;Albrechtshöhe;Alemannenstr.;Alexander-Herzen-Str.;Alexander-Puschkin-Platz;Alexanderstr.;Alfred-Althus-Str.;Alfred-Darre-Weg;Alfred-Schmieder-Str.;Alfred-Schrapel-Str.;Alfred-Thiele-Str.;Alnpeckstr.;Alpenstr.;Alsenstr.;Alt-Leu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string germanStreetNames {
            get {
                return ResourceManager.GetString("germanStreetNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron;Abbott;Abel;Abell;Abernathy;Abner;Abney;Abraham;Abrams;Abreu;Acevedo;Acker;Ackerman;Ackley;Acosta;Acuna;Adair;Adam;Adame;Adams;Adamson;Adcock;Addison;Adkins;Adler;Agee;Agnew;Aguayo;Aguiar;Aguilar;Aguilera;Aguirre;Ahern;Ahmad;Ahmed;Ahrens;Aiello;Aiken;Ainsworth;Akers;Akin;Akins;Alaniz;Alarcon;Alba;Albers;Albert;Albertson;Albrecht;Albright;Alcala;Alcorn;Alderman;Aldrich;Aldridge;Aleman;Alexander;Alfaro;Alfonso;Alford;Alfred;Alger;Ali;Alicea;Allan;Allard;Allen;Alley;Allison;Allman;Allred;Almanza;Almeida; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lastNames {
            get {
                return ResourceManager.GetString("lastNames", resourceCulture);
            }
        }
    }
}
