//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tynamix.ObjectFiller.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tynamix.ObjectFiller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aaron;Abbey;Abbie;Abby;Abdul;Abe;Abel;Abigail;Abraham;Abram;Ada;Adah;Adalberto;Adaline;Adam;Adam;Adan;Addie;Adela;Adelaida;Adelaide;Adele;Adelia;Adelina;Adeline;Adell;Adella;Adelle;Adena;Adina;Adolfo;Adolph;Adria;Adrian;Adrian;Adriana;Adriane;Adrianna;Adrianne;Adrien;Adriene;Adrienne;Afton;Agatha;Agnes;Agnus;Agripina;Agueda;Agustin;Agustina;Ahmad;Ahmed;Ai;Aida;Aide;Aiko;Aileen;Ailene;Aimee;Aisha;Aja;Akiko;Akilah;Al;Alaina;Alaine;Alan;Alana;Alane;Alanna;Alayna;Alba;Albert;Albert;Alberta;Albertha;Albertina;Al [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string firstNames {
            get {
                return ResourceManager.GetString("firstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aaron;Abbott;Abel;Abell;Abernathy;Abner;Abney;Abraham;Abrams;Abreu;Acevedo;Acker;Ackerman;Ackley;Acosta;Acuna;Adair;Adam;Adame;Adams;Adamson;Adcock;Addison;Adkins;Adler;Agee;Agnew;Aguayo;Aguiar;Aguilar;Aguilera;Aguirre;Ahern;Ahmad;Ahmed;Ahrens;Aiello;Aiken;Ainsworth;Akers;Akin;Akins;Alaniz;Alarcon;Alba;Albers;Albert;Albertson;Albrecht;Albright;Alcala;Alcorn;Alderman;Aldrich;Aldridge;Aleman;Alexander;Alfaro;Alfonso;Alford;Alfred;Alger;Ali;Alicea;Allan;Allard;Allen;Alley;Allison;Allman;Allred;Almanza;Almeida; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string lastNames {
            get {
                return ResourceManager.GetString("lastNames", resourceCulture);
            }
        }
    }
}
